twitter:
 name: 'Ticketing system11467'
 consumer_key: '2K763Dgw9y6oAOOLsegegkHW7'
 consumer_secret: 'pwXauJeR628SL8DhgwikStNYykGCKoabISHI4ZUnKIxt2eSmNY'
 oauth_token: '614156807-NgamApwuu0IGkXJQdFCdGazDU2WBIKWlnVXF1IaZ'
 oauth_token_secret: 'AjPuzPxfGQpTfhIDeWGoL5dzngzrvFYjH33TtoAwpkz0V'
